import { Body, Controller, Delete, Get, Param, Patch, Post, Query, Req, UnauthorizedException, UploadedFile, UseGuards, UseInterceptors } from '@nestjs/common';import { FileInterceptor } from '@nestjs/platform-express';import { ApiBearerAuth, ApiConsumes, ApiTags } from '@nestjs/swagger';import { Request } from 'express';import { JwtAuthGuard } from '../auth/jwt-auth.guard';import { Roles } from '../common/decorators/roles.decorator';import { Role } from '../common/enums/roles.enum';import { RolesGuard } from '../common/guards/roles.guard';import { CreateWebsiteContentDto, ReorderWebsiteContentDto, UpdateWebsiteContentDto } from './dto/website-content.dto';import { ContentStatus, ContentType } from './website-content.schema';import { WebsiteContentService } from './website-content.service';
type AdminRequest=Request&{user?:{sub?:string}};
@ApiTags('Website Content')@Controller('website-content')export class WebsiteContentController{constructor(private readonly service:WebsiteContentService){}
@Get()publicList(@Query('type')type?:ContentType){return this.service.publicList(type);}@Get('slug/:slug')publicBySlug(@Param('slug')slug:string){return this.service.publicBySlug(slug);}
@Get('admin/all')@UseGuards(JwtAuthGuard,RolesGuard)@Roles(Role.ADMIN)@ApiBearerAuth()adminList(@Query('type')type?:ContentType,@Query('status')status?:ContentStatus){return this.service.adminList(type,status);}
@Post('admin')@UseGuards(JwtAuthGuard,RolesGuard)@Roles(Role.ADMIN)@ApiBearerAuth()create(@Req()req:AdminRequest,@Body()dto:CreateWebsiteContentDto){return this.service.create(this.user(req),dto);}
@Patch('admin/reorder')@UseGuards(JwtAuthGuard,RolesGuard)@Roles(Role.ADMIN)@ApiBearerAuth()reorder(@Body()dto:ReorderWebsiteContentDto){return this.service.reorder(dto);}
@Post('admin/images')@UseGuards(JwtAuthGuard,RolesGuard)@Roles(Role.ADMIN)@ApiBearerAuth()@ApiConsumes('multipart/form-data')@UseInterceptors(FileInterceptor('image'))upload(@UploadedFile()file:Express.Multer.File){return this.service.uploadImage(file);}
@Patch('admin/:id')@UseGuards(JwtAuthGuard,RolesGuard)@Roles(Role.ADMIN)@ApiBearerAuth()update(@Req()req:AdminRequest,@Param('id')id:string,@Body()dto:UpdateWebsiteContentDto){return this.service.update(this.user(req),id,dto);}
@Delete('admin/:id')@UseGuards(JwtAuthGuard,RolesGuard)@Roles(Role.ADMIN)@ApiBearerAuth()remove(@Param('id')id:string){return this.service.remove(id);}
private user(req:AdminRequest){if(!req.user?.sub)throw new UnauthorizedException();return req.user.sub;}}
