import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';import { InjectModel } from '@nestjs/mongoose';import { Model, Types } from 'mongoose';import { CloudinaryService } from '../cloudinary/cloudinary.service';import { CreateWebsiteContentDto, ReorderWebsiteContentDto, UpdateWebsiteContentDto } from './dto/website-content.dto';import { ContentStatus, ContentType, WebsiteContent, WebsiteContentDocument } from './website-content.schema';
@Injectable()export class WebsiteContentService{constructor(@InjectModel(WebsiteContent.name)private readonly model:Model<WebsiteContentDocument>,private readonly cloudinary:CloudinaryService){}
publicList(type?:ContentType){const filter:Record<string,unknown>={status:ContentStatus.Published};if(type)filter.type=type;return this.model.find(filter).sort({displayOrder:1,publishedAt:-1}).select('-createdBy -updatedBy').exec();}
async publicBySlug(slug:string){const item=await this.model.findOne({slug:slug.toLowerCase(),status:ContentStatus.Published}).select('-createdBy -updatedBy').exec();if(!item)throw new NotFoundException('Published website content not found');return item;}
adminList(type?:ContentType,status?:ContentStatus){const filter:Record<string,unknown>={};if(type)filter.type=type;if(status)filter.status=status;return this.model.find(filter).sort({type:1,displayOrder:1,updatedAt:-1}).populate('createdBy updatedBy','name email').exec();}
async create(userId:string,dto:CreateWebsiteContentDto){this.id(userId);try{return await this.model.create({...dto,slug:this.slug(dto.slug),createdBy:new Types.ObjectId(userId),updatedBy:new Types.ObjectId(userId),publishedAt:dto.status===ContentStatus.Published?new Date():undefined});}catch(error){if((error as{code?:number}).code===11000)throw new ConflictException('Content slug already exists');throw error;}}
async update(userId:string,id:string,dto:UpdateWebsiteContentDto){this.id(userId);this.id(id);const set:Record<string,unknown>={...dto,updatedBy:new Types.ObjectId(userId)};if(dto.slug)set.slug=this.slug(dto.slug);if(dto.status===ContentStatus.Published)set.publishedAt=new Date();try{const item=await this.model.findByIdAndUpdate(id,{$set:set},{new:true,runValidators:true}).exec();if(!item)throw new NotFoundException('Website content not found');return item;}catch(error){if((error as{code?:number}).code===11000)throw new ConflictException('Content slug already exists');throw error;}}
async remove(id:string){this.id(id);const item=await this.model.findByIdAndDelete(id).exec();if(!item)throw new NotFoundException('Website content not found');return{deleted:true,id};}
async reorder(dto:ReorderWebsiteContentDto){for(const row of dto.items){this.id(row.id);if(!Number.isInteger(row.displayOrder)||row.displayOrder<0)throw new BadRequestException('Invalid display order');}await this.model.bulkWrite(dto.items.map((row)=>({updateOne:{filter:{_id:new Types.ObjectId(row.id)},update:{$set:{displayOrder:row.displayOrder}}}})));return{updated:dto.items.length};}
uploadImage(file:Express.Multer.File){return this.cloudinary.uploadImage(file,'decoho/website-content');}
private slug(value:string){return value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}private id(value:string){if(!Types.ObjectId.isValid(value))throw new BadRequestException('Invalid object id');}}
