import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';import { Model, Types } from 'mongoose';
import { CreateReviewDto, ModerateReviewDto, ReportReviewDto, ResolveReviewReportDto } from './dto/review.dto';import { Review, ReviewDocument, ReviewStatus } from './review.schema';
import { Product, ProductDocument } from '../products/product.schema';
@Injectable()export class ReviewsService{
constructor(@InjectModel(Review.name)private readonly model:Model<ReviewDocument>,@InjectModel(Product.name)private readonly products:Model<ProductDocument>){}
listPublic(productId?:string){const filter:Record<string,unknown>={status:ReviewStatus.Visible};if(productId){this.id(productId);filter.productId=new Types.ObjectId(productId);}return this.model.find(filter).sort({createdAt:-1}).populate('userId','name avatarUrl').exec();}
async create(userId:string,dto:CreateReviewDto){this.id(userId);const product=await this.products.findById(dto.productId).select('supplierId').exec();if(!product)throw new NotFoundException('Product not found');if(!product.supplierId)throw new BadRequestException('Product does not have a supplier');return this.model.create({...dto,userId:new Types.ObjectId(userId),productId:product._id,supplierId:product.supplierId,orderId:dto.orderId?new Types.ObjectId(dto.orderId):undefined});}
async report(userId:string,id:string,dto:ReportReviewDto){this.id(userId);this.id(id);const item=await this.model.findByIdAndUpdate(id,{$push:{reports:{userId:new Types.ObjectId(userId),reason:dto.reason,createdAt:new Date()}}},{new:true}).exec();if(!item)throw new NotFoundException('Review not found');return item;}
adminList(filters:{productId?:string;supplierId?:string;status?:ReviewStatus;reported?:boolean}){const query:Record<string,unknown>={};if(filters.productId){this.id(filters.productId);query.productId=new Types.ObjectId(filters.productId);}if(filters.supplierId){this.id(filters.supplierId);query.supplierId=new Types.ObjectId(filters.supplierId);}if(filters.status)query.status=filters.status;if(filters.reported)query['reports.0']={$exists:true};return this.model.find(query).sort({createdAt:-1}).populate('userId','name email avatarUrl').populate('productId','name image').populate('supplierId','name email').exec();}
hide(adminId:string,id:string,dto:ModerateReviewDto){return this.moderate(adminId,id,ReviewStatus.Hidden,dto.reason);}
deleteSpam(adminId:string,id:string,dto:ModerateReviewDto){return this.moderate(adminId,id,ReviewStatus.SpamDeleted,dto.reason);}
restore(adminId:string,id:string){return this.moderate(adminId,id,ReviewStatus.Visible,'Restored by admin');}
async resolveReport(adminId:string,id:string,dto:ResolveReviewReportDto){this.id(adminId);this.id(id);this.id(dto.reportId);const item=await this.model.findOneAndUpdate({_id:new Types.ObjectId(id),'reports._id':new Types.ObjectId(dto.reportId)},{$set:{'reports.$.resolved':true,'reports.$.resolution':dto.resolution,moderatedBy:new Types.ObjectId(adminId),moderatedAt:new Date()}},{new:true}).exec();if(!item)throw new NotFoundException('Review report not found');return item;}
private async moderate(adminId:string,id:string,status:ReviewStatus,reason:string){this.id(adminId);this.id(id);const item=await this.model.findByIdAndUpdate(id,{$set:{status,moderationReason:reason,moderatedBy:new Types.ObjectId(adminId),moderatedAt:new Date()}},{new:true}).exec();if(!item)throw new NotFoundException('Review not found');return item;}
private id(value:string){if(!Types.ObjectId.isValid(value))throw new BadRequestException('Invalid object id');}}
