import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';import { InjectModel } from '@nestjs/mongoose';import { Model, Types } from 'mongoose';
import { normalizeRole, Role } from '../common/enums/roles.enum';import { User, UserDocument } from '../users/user.schema';import { AssignTicketDto, CreateTicketDto, ReplyTicketDto, SetTicketPriorityDto, UpdateTicketStatusDto } from './dto/support-ticket.dto';import { SupportTicket, SupportTicketDocument, TicketStatus } from './support-ticket.schema';
@Injectable()export class SupportTicketsService{constructor(@InjectModel(SupportTicket.name)private readonly model:Model<SupportTicketDocument>,@InjectModel(User.name)private readonly users:Model<UserDocument>){}
create(userId:string,dto:CreateTicketDto){this.id(userId);const now=new Date();return this.model.create({ticketCode:`TKT-${now.getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`,title:dto.title,type:dto.type,customerId:new Types.ObjectId(userId),supplierId:dto.supplierId?new Types.ObjectId(dto.supplierId):undefined,orderId:dto.orderId?new Types.ObjectId(dto.orderId):undefined,messages:[{senderId:new Types.ObjectId(userId),content:dto.message,attachments:dto.attachments??[],createdAt:now}],statusHistory:[{status:TicketStatus.Open,changedBy:new Types.ObjectId(userId),at:now}]});}
myTickets(userId:string){this.id(userId);return this.model.find({$or:[{customerId:new Types.ObjectId(userId)},{supplierId:new Types.ObjectId(userId)}]}).sort({createdAt:-1}).populate('assignedStaffId','name email').exec();}
async reply(userId:string,id:string,dto:ReplyTicketDto,isAdmin=false){this.id(userId);this.id(id);const filter:Record<string,unknown>={_id:new Types.ObjectId(id)};if(!isAdmin)filter.$or=[{customerId:new Types.ObjectId(userId)},{supplierId:new Types.ObjectId(userId)}];const item=await this.model.findOneAndUpdate(filter,{$push:{messages:{senderId:new Types.ObjectId(userId),content:dto.content,attachments:dto.attachments??[],createdAt:new Date()}}},{new:true}).exec();if(!item)throw new ForbiddenException('Ticket not found or access denied');return item;}
adminList(filters:{status?:string;priority?:string;staffId?:string}){const query:Record<string,unknown>={};if(filters.status)query.status=filters.status;if(filters.priority)query.priority=filters.priority;if(filters.staffId){this.id(filters.staffId);query.assignedStaffId=new Types.ObjectId(filters.staffId);}return this.model.find(query).sort({priority:-1,createdAt:-1}).populate('customerId','name email').populate('supplierId','name email').populate('assignedStaffId','name email').populate('messages.senderId','name role').exec();}
async assign(id:string,dto:AssignTicketDto){this.id(id);const staff=await this.users.findById(dto.staffId).select('role').exec();const role=normalizeRole(staff?.role);if(!staff||!role||![Role.STAFF,Role.ADMIN,Role.SUPER_ADMIN].includes(role))throw new BadRequestException('Assignee must be staff or admin');return this.update(id,{assignedStaffId:new Types.ObjectId(dto.staffId),status:TicketStatus.InProgress});}
setPriority(id:string,dto:SetTicketPriorityDto){return this.update(id,{priority:dto.priority});}
async setStatus(adminId:string,id:string,dto:UpdateTicketStatusDto){this.id(adminId);this.id(id);const now=new Date();const set:Record<string,unknown>={status:dto.status};if(dto.status===TicketStatus.Resolved)set.resolvedAt=now;if(dto.status===TicketStatus.Closed)set.closedAt=now;const item=await this.model.findByIdAndUpdate(id,{$set:set,$push:{statusHistory:{status:dto.status,changedBy:new Types.ObjectId(adminId),at:now,note:dto.note}}},{new:true}).exec();if(!item)throw new NotFoundException('Ticket not found');return item;}
private async update(id:string,set:Record<string,unknown>){this.id(id);const item=await this.model.findByIdAndUpdate(id,{$set:set},{new:true,runValidators:true}).exec();if(!item)throw new NotFoundException('Ticket not found');return item;}private id(value:string){if(!Types.ObjectId.isValid(value))throw new BadRequestException('Invalid object id');}}
